# Generated by Django 5.2.7 on 2025-11-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reportnonuser_title_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.CharField(default='Unnamed Notification', max_length=50),
        ),
    ]
