# Generated by Django 5.2.7 on 2025-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='reported_object',
            field=models.CharField(default='User', max_length=4),
        ),
    ]
