# Generated by Django 5.2.7 on 2025-11-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reportuser_reported_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportuser',
            old_name='reported_user',
            new_name='reported_author',
        ),
    ]
