# Generated by Django 5.2.7 on 2025-12-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='userprofile/default_user.png', null=True, upload_to='userprofile/'),
        ),
    ]
