# Generated by Django 5.2.7 on 2025-12-12 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notification_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportnonuser',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportnonuser',
            name='appeal_message',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportnonuser',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportnonuser',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_nonuser_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportnonuser',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under review', 'Under review'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='appeal_message',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_user_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportuser',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under review', 'Under review'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20),
        ),
    ]
